### PR TITLE
Dismiss dropdown with browser back button 

### PR DESCRIPTION
**Pull request by nerdlet**
## Description

Resolves # 167813315
http://g.recordit.co/zkftE5lcom.gif

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by nerdlet** [comment]
@karimkawambwa Pushed the changes here

**Comment by karimkawambwa** [comment]
@kilemensi @nerdlet  please review my modal rework

**Comment by karimkawambwa** [comment]
> Still doesn't work as expected @karimkawambwa

@kilemensi does it work at times and then fails.
I don't know why the state variable always goes missing :/.

**Comment by karimkawambwa** [comment]
@kilemensido you know why the state sometimes `e.state.state` is null and sometimes its set correctly to `e.state.state === 'modal'`. It randomly stops working at times.

**Comment by karimkawambwa** [comment]
@kilemensi 

I have resolved the issue.

The problem was that pop state only gives you the current state and not the previous state as I originally thought. It worked sometimes because the href on `Contact` button caused the current state to be set to modal a.k.a 2 push states happen so I had to set the `Contact button` to have no href (href === undefined).

Since we do not know the previous state I have two options:

- do history replaceState('no-modal', ...)
- then history.pushState(...)
- on history.back(...) onpopstate I would get the event.state === 'no-modal'

Or 

- do history.pushState(...)
- on history.back(...) onpopstate I would not care what state am going back to, as long as modal is open, close it.

I went with the second option because we always push 1 state up regardless. So moving back we are always going back to a state without a modal.

**Comment by kilemensi** [comment]
Lets resolve the conflicts @karimkawambwa.

**Comment by karimkawambwa** [comment]
@kilemensi resolved

**Comment by karimkawambwa** [comment]
> useModalPopstate should probably be more explicit to indicate what happens to the Modal on Popstate to go with useToggleModal... e.g. useCloseModalOnPopstate, etc.

I think it is then worth having useToggleModal and useCloseModalOnPopstate in one file.

**Pull request merged**
