### PR TITLE
Profile tab and profile detail skeleton loader

### PR DESCRIPTION
**Pull request by karimkawambwa**

### CODE REVIEW

**Comment by DavidLemayian** [comment]
Sizing also looks a bit off for the content. The heights should kinda match.

**Comment by karimkawambwa** [comment]
@DavidLemayian 

```
Let's add the following components to have a loading state:

The map
The section filters
Skeletons of card decks with charts (titles et al)
```

The map loading will need a callback so that will be a separate story.

> Sizing also looks a bit off for the content. The heights should kinda match.

I don't think the sizing should match 100%, there will be some offset but I'll tweak it. do look at it with some threshold.

**Comment by karimkawambwa** [comment]
@DavidLemayian this gif is a bit I believe leaflet was also slow even in returning the base layers of the map. 

I have added the chart loader here https://github.com/CodeForAfrica/HURUmap-UI/pull/44

**Comment by karimkawambwa** [comment]
@kilemensi could I get a review here. keep in might that the chartcontainer loader is coming from hurumap-ui once its published. also we will you the Contentloaders/BloackLoader from hurumap-ui once its published.

**Comment by DavidLemayian** [comment]
@karimkawambwa screenshot for the charts section on this page?

**Comment by karimkawambwa** [comment]
@DavidLemayian it will only become available after hurumap-ui is published.

The loader skeleton will look like below:

Screen Shot 2019-08-23 at 12 47 29 PM

**Comment by DavidLemayian** [comment]
@karimkawambwa who's publishing HURUmap-UI? Should I do that?

**Comment by karimkawambwa** [comment]
@DavidLemayian waiting for @kilemensi to fish his PR.

**Pull request merged**
